// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),

ACMD_DEF(gepard_block_nick),
ACMD_DEF(gepard_block_account_id),
ACMD_DEF(gepard_block_unique_id),
ACMD_DEF(gepard_unblock_nick),
ACMD_DEF(gepard_unblock_account_id),
ACMD_DEF(gepard_unblock_unique_id),
ACMD_DEF(offline),
