// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

BUILDIN_DEF(get_unique_id,""),
BUILDIN_DEF(get_mob_location,"i"),
BUILDIN_DEF(mob_name2id,"s"),
BUILDIN_DEF(getinventoryinfo, "ii?"),
BUILDIN_DEF(getitemcombatpower, "i?"),
BUILDIN_DEF(processhalt, "?"),
BUILDIN_DEF(checkoffline, "?"),
BUILDIN_DEF(login, "i????"),
BUILDIN_DEF(damage_log_query, "iii?"),
BUILDIN_DEF(damage_log_rank, "irri??"),
BUILDIN_DEF(log_damage_reset, "i"),
